Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2019-01, with the labels that each got.

#2517 Fix DataGrid colours not adapting to Dark Theme
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.xaml
Labels: DataGrid, controls, reviewers wanted

#2743 Fix behavior on queue behind and stack in front modes
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Labels: bug, controls, reviewers wanted

#2732 Replace CompositionSurfaceFactory with Platform API
  Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs
Labels: introduce breaking changes, reviewers wanted

#2536 Added Support for Incremental Loading in the DataGrid
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridDataConnection.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridRows.cs
Labels: DataGrid, controls, reviewers wanted

#2768 Disable TabStop property for AligmentGrid
  Microsoft.Toolkit.Uwp.DeveloperTools/AlignmentGrid/AlignmentGrid.cs
Labels: accessibility, controls, reviewers wanted

#2771 AlignmentGrid - Draw lines when the step value is greater than zero
  Microsoft.Toolkit.Uwp.DeveloperTools/AlignmentGrid/AlignmentGrid.cs
Labels: reviewers wanted

#2776 Fixed High Contrast Mode Crash
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.xaml
Labels: accessibility, reviewers wanted, sample app
