Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-06, with the labels that each got.

#3319 Mhawker/ttb updates
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TabView/TabViewPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.xaml
  Microsoft.Toolkit.Uwp.UI/Extensions/Tree/LogicalTree.cs
  Microsoft.Toolkit.Uwp.UI/Helpers/CompositionTargetHelper.cs
Labels: controls :control_knobs:, improvements :sparkles:

#3213 Improvements to AdaptiveGrid Sample page
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/AdaptiveGridView/AdaptiveGridViewPage.xaml.cs
Labels: open discussion :telephone:, sample app :iphone:

#3330 Fix crash with unbounded sizing for WrapLayout.
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayoutPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayout.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/WrapLayout.cs
Labels: bug :bug:

#3334 BitmapIconSource extension
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsXaml.bind
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/Abstract/TextIconExtension{T}.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/BitmapIconSourceExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/FontIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/FontIconSourceExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/SymbolIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/SymbolIconSourceExtension.cs
  UnitTests/UnitTests.UWP/UnitTestApp.xaml
Labels: improvements :sparkles:

#3337 Sample App Updates for Release
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/Package.appxmanifest
  Microsoft.Toolkit.Uwp.SampleApp/Properties/AssemblyInfo.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/NameToColorConverter.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/SampleEmailDataType.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ViewportBehavior/ViewportBehaviorPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.SampleApp/landingPageLinks.json
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/ITokenStringContainer.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Selection.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxStyleSelector.cs
Labels: bug :bug:, improvements :sparkles:, sample app :iphone:, sample bug :bug:

#3352 Xaml Islands Fixes for FocusManager.GetFocusedElement and ContentDial…
  Microsoft.Toolkit.Uwp.DeveloperTools/FocusTracker/FocusTracker.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.Search.cs
  Microsoft.Toolkit.Uwp.UI.Animations/ApiInformationHelper.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/QuickReturnHeaderBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Behaviors/StickyHeaderBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Utilities/Extensions.cs
  Microsoft.Toolkit.Uwp.UI.Controls/Carousel/Carousel.cs
  Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/Menu/Menu.Logic.cs
  Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitView.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TextToolbar/ToolbarItems/Common/CommonButtons.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Selection.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs
  UnitTests/UnitTests.XamlIslands.UWPApp/UnitTests.XamlIslands.UWPApp.csproj
  UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_TextToolbar.cs
  UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_TokenizingTextBox.cs
Labels: bug :bug:

#3365 Fixed local errors in .NET Core 2.1 unit tests
  UnitTests/UnitTests.NetCore/UnitTests.NetCore.csproj
Labels: auto merge
