Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-07, with the labels that each got.

#3374 DataGrid fixes for WinUI 3 usage
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridCell.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridColumnHeader.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridRowHeader.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Utilities/KeyboardHelper.cs
Labels: DataGrid :capital_abcd:, bug :bug:

#3357 Enum values markdown extension
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/EnumValuesExtensionCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/EnumValuesExtensionPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/EnumValuesExtensionPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/EnumValuesExtensionXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/EnumValuesExtension.cs
  UnitTests/UnitTests.UWP/Extensions/Test_EnumValuesExtension.cs
  UnitTests/UnitTests.UWP/Properties/UnitTestApp.rd.xml
  UnitTests/UnitTests.UWP/UnitTestApp.xaml
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: extensions :zap:, feature :bulb:, needs attention :wave:

#3191 Remove `Bindable` attribute to reduce binary size impact
  Microsoft.Toolkit.Uwp.UI.Controls/UniformGrid/UniformGrid.cs
  Microsoft.Toolkit.Uwp.UI/Converters/DoubleToObjectConverter.cs
  Microsoft.Toolkit.Uwp.UI/Converters/DoubleToVisibilityConverter.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/NullableBool.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/OnDevice.cs
  UnitTests/UnitTests.UWP/Extensions/Helpers/ObjectWithNullableBoolProperty.cs
  UnitTests/UnitTests.UWP/UnitTestApp.xaml
Labels: auto merge

#3368 Remove `lock` statements from `InAppNotification` control
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/InAppNotification/InAppNotificationXaml.bind
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Constants.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/VSCodeNotificationStyle.xaml
Labels: auto merge, introduce breaking changes :boom:

#3375 Improve accessibility in InAppNotification
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/Styles/MSEdgeNotificationStyle.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/Strings/en-US/Resources.resw
Labels: accessibility :wheelchair:, auto merge, bug :bug:, controls :control_knobs:, improvements :sparkles:

#3395 Update PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto merge, documentation :page_with_curl:

#3388 fix a problem when parsing with ---\n---\n
  Microsoft.Toolkit.Parsers/Markdown/Blocks/YamlHeaderBlock.cs
  UnitTests/UnitTests.UWP/Markdown/Parse/HorizontalRuleTests.cs
Labels: bug :bug:
