Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-05, with the labels that each got.

#3256 .NET Core 3.0 support for desktop toasts
  Microsoft.Toolkit.Uwp.Notifications/DesktopNotificationManager/DesktopNotificationManagerCompat.cs
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
  ThirdPartyNotices.txt
Labels: reviewers wanted :raised_hand:

#3236 Update Readme feature list
  .github/PULL_REQUEST_TEMPLATE.md
  readme.md
Labels: documentation :page_with_curl:, for-review :book:

#3275 Add MasterDetailsView.SelectedIndex
  Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs
  UnitTests/UI/Controls/Test_MasterDetailsView.cs
  UnitTests/UnitTests.csproj
Labels: feature :bulb:

#3160 Add new WrapLayout and StaggeredLayout controls
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayout.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayout.png
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayoutPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayoutPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayout.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayout.png
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayoutPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj.DotSettings
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Properties/AssemblyInfo.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Properties/Microsoft.Windows.Toolkit.UI.Controls.Layout.rd.xml
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/StaggeredLayout/StaggeredColumnLayout.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/StaggeredLayout/StaggeredItem.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/StaggeredLayout/StaggeredLayout.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/StaggeredLayout/StaggeredLayoutState.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/VisualStudioToolsManifest.xml
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/UvBounds.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/UvMeasure.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/WrapItem.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/WrapLayout.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/WrapLayout/WrapLayoutState.cs
  Windows Community Toolkit.sln
Labels: WinUI :diamond_shape_with_a_dot_inside:, controls :control_knobs:, feature :bulb:

#3030 Initial port of WindowsStateTriggers to the UWP Toolkit.
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/CompareStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/CompareStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/CompareStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/FullScreenModeStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/FullScreenModeStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/FullScreenModeStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsEqualStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsEqualStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsEqualStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNotEqualStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNotEqualStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNotEqualStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNullOrEmptyStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNullOrEmptyStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/IsNullOrEmptyStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/NetworkConnectionStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/NetworkConnectionStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/NetworkConnectionStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/RegexStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/RegexStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/RegexStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserHandPreferenceStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserHandPreferenceStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserHandPreferenceStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserInteractionModeStateTrigger.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserInteractionModeStateTriggerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Triggers/UserInteractionModeStateTriggerPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI/Triggers/CompareStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/FullScreenModeStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/IsEqualStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/IsNotEqualStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/IsNullOrEmptyStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/NetworkConnectionStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/RegexStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/UserHandPreferenceStateTrigger.cs
  Microsoft.Toolkit.Uwp.UI/Triggers/UserInteractionModeStateTrigger.cs
Labels: feature :bulb:

#3247 Add the TokenizingTextBox control behaviours for initial commit
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/SampleDataType.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/SampleEmailDataType.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI.Controls/Themes/Generic.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/InterspersedObservableCollection.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/PretokenStringContainer.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenItemAddingEventArgs.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenItemRemovingEventArgs.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Selection.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.Token.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxStyleSelector.cs
  Microsoft.Toolkit.Uwp.UI.Controls/WrapPanel/WrapPanel.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.Selection.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.cs
  ThirdPartyNotices.txt
  UnitTests/UnitTests.UWP/PrivateObject.cs
  UnitTests/UnitTests.UWP/PrivateType.cs
  UnitTests/UnitTests.UWP/UI/Controls/Test_TokenizingTextBox_InterspersedCollection.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
  Windows Community Toolkit.sln
Labels: controls :control_knobs:

#3110 FontIcon markup extension
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/Abstract/TextIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/Abstract/TextIconExtension{T}.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/BitmapIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/FontIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/FontIconSourceExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/NullableBool.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/OnDevice.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/SymbolIconExtension.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/SymbolIconSourceExtension.cs
  Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
  UnitTests/UnitTests.UWP/Extensions/Test_BitmapIconExtensionMarkupExtension.cs
  UnitTests/UnitTests.UWP/Extensions/Test_FontIconExtensionMarkupExtension.cs
  UnitTests/UnitTests.UWP/Extensions/Test_FontIconSourceExtensionMarkupExtension.cs
  UnitTests/UnitTests.UWP/Properties/UnitTestApp.rd.xml
  UnitTests/UnitTests.UWP/UnitTestApp.xaml
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: feature :bulb:

#3238 Fixed callbacks unregistering in MarkdownTextBlock
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Labels: reviewers wanted :raised_hand:

#3276 Flush clipboard on suspending to preserve content
  Microsoft.Toolkit.Uwp.SampleApp/App.xaml.cs
Labels: for-review :book:, improvements :sparkles:

#3301 Update NuGet Dependencies & Clean-up
  Directory.Build.props
  Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayout.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/StaggeredLayout/StaggeredLayoutPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/WrapLayout/WrapLayout.bind
  Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.Search.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml
  Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj
  Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
  Microsoft.Toolkit.Uwp.UI.Media/Microsoft.Toolkit.Uwp.UI.Media.csproj
  UnitTests/UnitTests.Notifications.NetCore/UnitTests.Notifications.NetCore.csproj
  UnitTests/UnitTests.Notifications.WinRT/UnitTests.Notifications.WinRT.csproj
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
  azure-pipelines.yml
  build/build.cake
Labels: improvements :sparkles:

#2919 Added support for binding to sub-objects in ComboBoxColumn
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridComboBoxColumn.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridError.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Utilities/TypeHelper.cs
Labels: DataGrid :capital_abcd:, reviewers wanted :raised_hand:

#3309 Enabled deterministic builds.
  Directory.Build.props
  Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj
  Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Labels: feature request :mailbox_with_mail:

#3307 Removed full pdb workaround, switching to portable pdbs.
  Directory.Build.targets
  Microsoft.Toolkit.HighPerformance/Microsoft.Toolkit.HighPerformance.csproj
  Microsoft.Toolkit.Parsers/Microsoft.Toolkit.Parsers.csproj
  Microsoft.Toolkit.Services/Microsoft.Toolkit.Services.csproj
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
  Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer.csproj
  Microsoft.Toolkit/Microsoft.Toolkit.csproj
Labels: auto merge

#3209 Making the ListExtensions feature in-line with the documentation
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListViewExtensions/ListViewExtensionsPage.xaml.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.Command.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/ListViewBase/ListViewExtensions.cs
Labels: auto merge

#3310 tokenize text box polish
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/SampleEmailDataType.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/TokenizingTextBox/TokenizingTextBoxXaml.bind
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/ITokenStringContainer.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/PretokenStringContainer.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.Selection.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBox.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.xaml
Labels: auto merge, improvements :sparkles:

#3306 Fix for #2899.
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
Labels: auto merge, bug :bug:

#3291 Update to WinUI 2.4
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
  Microsoft.Toolkit.Uwp.SampleApp/Styles/Generic.xaml
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj
  Microsoft.Toolkit.Uwp.UI.Controls/TokenizingTextBox/TokenizingTextBoxItem.AutoSuggestBox.xaml
Labels: auto merge, build :fire:, improvements :sparkles:, sample app :iphone:

#3315 Deprecate TabView, RadialGradientBrush, Singleton, FacebookService
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookService.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TabView/TabView.cs
  Microsoft.Toolkit.Uwp.UI.Media/Brushes/RadialGradientBrush.cs
  Microsoft.Toolkit/Helpers/Singleton.cs
Labels: auto merge

#3313 Fixed strong name signing.
  Directory.Build.props
  Directory.Build.targets
  toolkit.public.snk
Labels: auto merge, bug :bug:

#3316 Fixed an XML summary
  Microsoft.Toolkit.Uwp.UI.Media/Brushes/PipelineBrush.cs
Labels: documentation :page_with_curl:
