Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-03, with the labels that each got.

#3153 Fix RadialGauge default template value formatting
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/RadialGauge/RadialGaugeCode.bind
  Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.cs
  Microsoft.Toolkit.Uwp.UI.Controls/RadialGauge/RadialGauge.xaml
Labels: bug :bug:, controls :control_knobs:

#3131 Guard APIs
  .gitignore
  Microsoft.Toolkit/Converters.cs
  Microsoft.Toolkit/Diagnostics/Generated/Guard.Collection.g.cs
  Microsoft.Toolkit/Diagnostics/Generated/Guard.Collection.tt
  Microsoft.Toolkit/Diagnostics/Generated/Guard.Comparable.Numeric.g.cs
  Microsoft.Toolkit/Diagnostics/Generated/Guard.Comparable.Numeric.tt
  Microsoft.Toolkit/Diagnostics/Generated/Guard.md
  Microsoft.Toolkit/Diagnostics/Generated/ThrowHelper.Collection.g.cs
  Microsoft.Toolkit/Diagnostics/Generated/ThrowHelper.Collection.tt
  Microsoft.Toolkit/Diagnostics/Generated/TypeInfo.ttinclude
  Microsoft.Toolkit/Diagnostics/Guard.Comparable.Generic.cs
  Microsoft.Toolkit/Diagnostics/Guard.Comparable.Numeric.cs
  Microsoft.Toolkit/Diagnostics/Guard.IO.cs
  Microsoft.Toolkit/Diagnostics/Guard.String.cs
  Microsoft.Toolkit/Diagnostics/Guard.Tasks.cs
  Microsoft.Toolkit/Diagnostics/Guard.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.Collection.Generic.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.Comparable.Generic.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.Comparable.Numeric.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.IO.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.String.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.Tasks.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.ThrowExceptions.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.cs
  Microsoft.Toolkit/Extensions/ArrayExtensions.cs
  Microsoft.Toolkit/Extensions/TypeExtensions.cs
  Microsoft.Toolkit/Extensions/ValueTypeExtensions.cs
  Microsoft.Toolkit/IncrementalLoadingCollection/IIncrementalSource.cs
  Microsoft.Toolkit/Microsoft.Toolkit.csproj
  UnitTests/Diagnostics/Test_Guard.Array.cs
  UnitTests/Diagnostics/Test_Guard.Comparable.Numeric.cs
  UnitTests/Diagnostics/Test_Guard.cs
  UnitTests/Extensions/Test_TypeExtensions.cs
  UnitTests/Extensions/Test_ValueTypeExtensions.cs
  UnitTests/UnitTests.csproj
Labels: feature :bulb:, for-review :book:, helpers :raised_hand:, needs attention :wave:

#3115 Add Dependency Info
  readme.md
Labels: documentation :page_with_curl:, need more info :pushpin:, needs attention :wave:

#3168 Change SystemInformation from static to regular class
  Microsoft.Toolkit.Uwp.SampleApp/App.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/SystemInformation/SystemInformationPage.xaml.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/Markup/OnDevice.cs
  Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs
Labels: improvements :sparkles:, introduce breaking changes :boom:, needs attention :wave:

#3117 Fix "Italic" checkstate bug + fix "italic" typo in InfiniteCanvas control
  Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.TextBox.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InfiniteCanvas/InfiniteCanvas.xaml
Labels: needs author feedback :memo:

#3181 Let BaseObjectStorageHelper use custom JsonSerializerOptions
  Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs
  Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/IObjectSerializer.cs
  Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/JsonObjectSerializer.cs
  Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/LocalObjectStorageHelper.cs
  Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/RoamingObjectStorageHelper.cs
Labels: needs attention :wave:

#3119 Dispatcher helper optimizations
  Microsoft.Toolkit.Uwp/Helpers/DispatcherHelper.cs
  UnitTests/Helpers/Test_DispatcherHelper.cs
  UnitTests/UnitTests.csproj
Labels: need more info :pushpin:

#3180 [Bug fix] Fixed a bug where MarkdownTextBlock loses all events after …
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.Methods.cs
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.cs
Labels: needs attention :wave:
