Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-12, with the labels that each got.

#3592 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto merge, documentation :page_with_curl:

#3596 Removed leftover DispatcherQueue usages
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/DispatcherQueueHelper/DispatcherQueueHelperPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.SamplePicker.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.Search.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Extensions/AnimationExtensions.Light.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/ScrollViewer/ScrollViewerExtensions.MiddleClickScrolling.cs
  Microsoft.Toolkit.Uwp/Extensions/DispatcherQueueExtensions.cs
  UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_Gaze.cs
Labels: auto merge, extensions :zap:, in progress :construction:, maintenance :gear:

#3588 Added theme-specific background for XAML code errors
  Microsoft.Toolkit.Uwp.SampleApp/Controls/XamlCodeEditor.xaml.cs
Labels: auto merge, bug :bug:, in progress :construction:, sample app :iphone:

#3604 Add unary operator
  Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionFunctions.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ExpressionNode.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Expressions/OperationType.cs
Labels: animations :izakaya_lantern:, auto merge, bug :bug:, extensions :zap:

#3608 Improved RuntimeHelpers.ConvertLength codegen
  Microsoft.Toolkit.HighPerformance/Helpers/Internals/RuntimeHelpers.cs
Labels: .NET Standard, auto merge, high-performance 🚂, optimization ☄

#3605 Add extensions support for CompositionConditionalValue
  Microsoft.Toolkit.Uwp.UI.Animations/Expressions/CompositionExtensions.cs
Labels: auto merge, in progress :construction:

#3601 Fix Debug AnyCPU config for XamlIslands Package Unit Test
  Windows Community Toolkit.sln
Labels: auto merge, bug :bug:, build :fire:, in progress :construction:

#3590 Create separate instances of GazePointer per (UI) thread,
  Microsoft.Toolkit.Uwp.Input.GazeInteraction/GazePointer.cs
Labels: auto merge, bug :bug:, in progress :construction:

#3582 Reset Notifications min version to 10240
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
Labels: auto merge, in progress :construction:, reviewers wanted :raised_hand:

#3612 Normalize tilecontrol
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/ImageAlignment.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/ScrollOrientation.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs
Labels: auto merge

#3611 Remove animations from RangeSelector
  Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.cs
  Microsoft.Toolkit.Uwp.UI.Controls/RangeSelector/RangeSelector.xaml
  Microsoft.Toolkit.Uwp.UI/Extensions/DispatcherQueueTimerExtensions.cs
Labels: animations :izakaya_lantern:, auto merge, for-review :book:, introduce breaking changes :boom:, reviewers wanted :raised_hand:, sample app :iphone:

#3580 Test app service in CI
  UITests/UITests.App/App.AppService.xaml.cs
  UITests/UITests.App/App.xaml
  UITests/UITests.App/App.xaml.cs
  UITests/UITests.App/MainPage.xaml
  UITests/UITests.App/MainPage.xaml.cs
  UITests/UITests.App/MainTestHost.xaml
  UITests/UITests.App/MainTestHost.xaml.cs
  UITests/UITests.App/Package.appxmanifest
  UITests/UITests.App/RequestPageMessage.cs
  UITests/UITests.App/TestInterop.cs
  UITests/UITests.App/UITests.App.csproj
  UITests/UITests.Tests.MSTest/MSTestInterop.cs
  UITests/UITests.Tests.MSTest/UITests.Tests.MSTest.csproj
  UITests/UITests.Tests.Shared/Controls/TextBoxMaskTest.cs
  UITests/UITests.Tests.Shared/Controls/TextBoxMaskTestPage.xaml
  UITests/UITests.Tests.Shared/Controls/TextBoxMaskTestPage.xaml.cs
  UITests/UITests.Tests.Shared/Examples/SimpleTest.cs
  UITests/UITests.Tests.Shared/Examples/SimpleTestPage.xaml
  UITests/UITests.Tests.Shared/Examples/SimpleTestPage.xaml.cs
  UITests/UITests.Tests.Shared/TestAssembly.cs
  UITests/UITests.Tests.Shared/TestPageAttribute.cs
  UITests/UITests.Tests.Shared/Tests.cs
  UITests/UITests.Tests.Shared/UITestBase.cs
  UITests/UITests.Tests.Shared/UITests.Tests.Shared.projitems
  UITests/UITests.Tests.TAEF/UITests.Tests.TAEF.csproj
  UnitTests/UnitTests.XamlIslands.UWPApp/XamlIslandsTest_SystemInformation.cs
  Windows Community Toolkit.sln
Labels: CI/pipeline 🔬, auto merge, improvements :sparkles:, testing :building_construction:

#3518 Added automation peers for BladeView and BladeItem controls
  Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeItem.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeItem.cs
  Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeItemAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeView.cs
  Microsoft.Toolkit.Uwp.UI.Controls/BladeView/BladeViewAutomationPeer.cs
  UnitTests/UnitTests.UWP/UI/Controls/Test_BladeView.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: bug :bug:

#3617 Split out Smoke Tests and Unit Tests into a separate Jobs
  SmokeTests/SmokeTest.csproj
  SmokeTests/SmokeTestAnalysis.ps1
  SmokeTests/SmokeTests.proj
  SmokeTests/UWPBaseline/MainPage.xaml
  SmokeTests/UWPBaseline/MainPage.xaml.cs
  azure-pipelines.yml
  build/build.cake
Labels: CI/pipeline 🔬, auto merge, build :fire:, improvements :sparkles:, in progress :construction:, reviewers wanted :raised_hand:, testing :building_construction:

#3627 Orbitview remove animation expressions
  Microsoft.Toolkit.Uwp.UI.Controls/OrbitView/OrbitView.cs
Labels: auto merge, controls :control_knobs:, in progress :construction:, reviewers wanted :raised_hand:

#3633 TileControl: Remove Animations.Expressions usage
  Microsoft.Toolkit.Uwp.UI.Controls/TileControl/TileControl.cs
Labels: animations :izakaya_lantern:, auto merge :zap:, in progress :construction:

#3630 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto merge :zap:, documentation :page_with_curl:, improvements :sparkles:

#3634 Creating `Microsoft.Toolkit.Uwp.UI.Behaviors`
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/FadeHeader/FadeHeaderBehaviorPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/FadeHeader/FadeHeaderBehaviorXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/IconExtensions/IconExtensionsPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Implicit Animations/ImplicitAnimationsCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/LoginButton/LoginButtonPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/OnDevice/OnDevicePage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PeoplePicker/PeoplePickerPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/PersonView/PersonViewPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollHeader/ScrollHeaderCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollHeader/ScrollHeaderPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollViewerExtensions/ScrollViewerExtensionsPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ScrollViewerExtensions/ScrollViewerExtensionsXaml.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ViewportBehavior/ViewportBehaviorPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/Shell.xaml
  Microsoft.Toolkit.Uwp.SampleApp/Styles/Custom/PivotHeaderItemUnderlineStyle.xaml
  Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj
  Microsoft.Toolkit.Uwp.UI.Animations/SurfaceLoader.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/ApiInformationHelper.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/BehaviorBase.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Focus/AutoFocusBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Focus/FocusBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Headers/FadeHeaderBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Headers/QuickReturnHeaderBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Headers/StickyHeaderBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Behaviors/Microsoft.Toolkit.Uwp.UI.Behaviors.csproj
  Microsoft.Toolkit.Uwp.UI.Behaviors/Properties/Microsoft.Toolkit.Uwp.UI.Behaviors.rd.xml
  Microsoft.Toolkit.Uwp.UI.Behaviors/Viewport/ViewportBehavior.cs
  Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
  Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.cs
  Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeader.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/ScrollHeader/ScrollHeaderMode.cs
  Microsoft.Toolkit.Uwp.UI.Controls/Themes/Generic.xaml
  Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
  SmokeTests/Microsoft.Toolkit.Uwp.UI.Behaviors/MainPage.xaml
  SmokeTests/Microsoft.Toolkit.Uwp.UI.Behaviors/MainPage.xaml.cs
  SmokeTests/Microsoft.Toolkit.Uwp.UI/MainPage.xaml
  SmokeTests/Microsoft.Toolkit.Uwp.UI/MainPage.xaml.cs
  SmokeTests/SmokeTests.proj
  Windows Community Toolkit.sln
Labels: animations :izakaya_lantern:, controls :control_knobs:, improvements :sparkles:, in progress :construction:, maintenance :gear:, needs attention :wave:, open discussion :telephone:
