Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-04, with the labels that each got.

#3193 UIElement.ClipToBounds property
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ClipToBounds/ClipToBoundsCode.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ClipToBounds/ClipToBoundsPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ClipToBounds/ClipToBoundsPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit.Uwp.UI/Extensions/UIElement/UIElementExtensions.cs
Labels: extensions :zap:, feature :bulb:, needs attention :wave:

#3192 Update Fixes in PR template to be a header
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation :page_with_curl:

#3201 Add observable group API
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ObservableGroup/ObservableGroup.bind
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ObservableGroup/ObservableGroupPage.xaml
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ObservableGroup/ObservableGroupPage.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
  Microsoft.Toolkit/Collections/IReadOnlyObservableGroup.cs
  Microsoft.Toolkit/Collections/ObservableGroup.cs
  Microsoft.Toolkit/Collections/ObservableGroupedCollection.cs
  Microsoft.Toolkit/Collections/ReadOnlyObservableGroup.cs
  Microsoft.Toolkit/Collections/ReadOnlyObservableGroupedCollection.cs
  UnitTests/Collections/IntGroup.cs
  UnitTests/Collections/ObservableGroupTests.cs
  UnitTests/Collections/ObservableGroupedCollectionTests.cs
  UnitTests/Collections/ReadOnlyObservableGroupTests.cs
  UnitTests/Collections/ReadOnlyObservableGroupedCollectionTests.cs
  UnitTests/UnitTests.csproj
Labels: for-review :book:, reviewers wanted :raised_hand:

#3234 Optimize Sample App Sample Loading
  Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
  Microsoft.Toolkit.Uwp.SampleApp/Models/Samples.cs
  Microsoft.Toolkit.Uwp.SampleApp/Pages/SampleController.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/samples.json
Labels: for-review :book:, improvements :sparkles:, sample app :iphone:

#3235 Upgrade Microsoft.Xaml.Behaviors.Uwp.Managed package
  Microsoft.Toolkit.Uwp.SampleApp/Microsoft.Toolkit.Uwp.SampleApp.csproj
  Microsoft.Toolkit.Uwp.UI.Animations/Microsoft.Toolkit.Uwp.UI.Animations.csproj
  Microsoft.Toolkit.Uwp.UI/Microsoft.Toolkit.Uwp.UI.csproj
Labels: for-review :book:
