Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2020-08, with the labels that each got.

#3229 Microsoft.Toolkit.Mvvm package
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
  Microsoft.Toolkit.Mvvm/DependencyInjection/Ioc.cs
  Microsoft.Toolkit.Mvvm/Input/AsyncRelayCommand.cs
  Microsoft.Toolkit.Mvvm/Input/AsyncRelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Input/Interfaces/IAsyncRelayCommand.cs
  Microsoft.Toolkit.Mvvm/Input/Interfaces/IAsyncRelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Input/Interfaces/IRelayCommand.cs
  Microsoft.Toolkit.Mvvm/Input/Interfaces/IRelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Input/RelayCommand.cs
  Microsoft.Toolkit.Mvvm/Input/RelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/IMessenger.cs
  Microsoft.Toolkit.Mvvm/Messaging/IRecipient{TMessage}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/AsyncCollectionRequestMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/AsyncRequestMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/CollectionRequestMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/PropertyChangedMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/RequestMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/ValueChangedMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messenger.cs
  Microsoft.Toolkit.Mvvm/Messaging/MessengerExtensions.Unit.cs
  Microsoft.Toolkit.Mvvm/Messaging/MessengerExtensions.cs
  Microsoft.Toolkit.Mvvm/Messaging/Microsoft.Collections.Extensions/DictionarySlim{TKey,TValue}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Microsoft.Collections.Extensions/HashHelpers.cs
  Microsoft.Toolkit.Mvvm/Messaging/Microsoft.Collections.Extensions/IDictionarySlim.cs
  Microsoft.Toolkit.Mvvm/Messaging/Microsoft.Collections.Extensions/IDictionarySlim{TKey,TValue}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Microsoft.Collections.Extensions/IDictionarySlim{TKey}.cs
  Microsoft.Toolkit.Mvvm/Microsoft.Toolkit.Mvvm.csproj
  Microsoft.Toolkit.Uwp.UI/Converters/TaskResultConverter.cs
  Microsoft.Toolkit/Attributes/MaybeNullAttribute.cs
  Microsoft.Toolkit/Extensions/TaskExtensions.cs
  Microsoft.Toolkit/Helpers/NotifyTaskCompletion.cs
  ThirdPartyNotices.txt
  UnitTests/Extensions/Test_TaskExtensions.cs
  UnitTests/UnitTests.NetCore/UnitTests.NetCore.csproj
  UnitTests/UnitTests.Shared/Extensions/Test_TaskExtensions.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_AsyncRelayCommand.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_Ioc.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_Messenger.Request.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_Messenger.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_ObservableObject.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_ObservableRecipient.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_RelayCommand.cs
  UnitTests/UnitTests.Shared/Mvvm/Test_RelayCommand{T}.cs
  UnitTests/UnitTests.Shared/UnitTests.Shared.projitems
  UnitTests/UnitTests.UWP/Converters/Test_TaskResultConverter.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
  Windows Community Toolkit.sln
Labels: .NET Standard, feature :bulb:, feature request :mailbox_with_mail:, open discussion :telephone:, reviewers wanted :raised_hand:

#3406 fix some spelling
  Microsoft.Toolkit.HighPerformance/Box{T}.cs
  Microsoft.Toolkit.HighPerformance/Extensions/ArrayExtensions.2D.cs
  Microsoft.Toolkit.HighPerformance/Extensions/MemoryExtensions.cs
  Microsoft.Toolkit.HighPerformance/Extensions/ObjectExtensions.cs
  Microsoft.Toolkit.HighPerformance/Extensions/ReadOnlyMemoryExtensions.cs
  Microsoft.Toolkit.HighPerformance/Extensions/ReadOnlySpanExtensions.cs
  Microsoft.Toolkit.HighPerformance/ReadOnlyRef{T}.cs
  Microsoft.Toolkit.HighPerformance/Ref{T}.cs
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
  Microsoft.Toolkit.Mvvm/DependencyInjection/Ioc.cs
  Microsoft.Toolkit.Mvvm/Input/Interfaces/IAsyncRelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Input/RelayCommand.cs
  Microsoft.Toolkit.Mvvm/Input/RelayCommand{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messages/PropertyChangedMessage{T}.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messenger.cs
  Microsoft.Toolkit.Mvvm/Messaging/MessengerExtensions.cs
  Microsoft.Toolkit.Parsers/Markdown/Blocks/ListBlock.cs
  Microsoft.Toolkit.Parsers/Markdown/Blocks/TableBlock.cs
  Microsoft.Toolkit.Parsers/Markdown/Blocks/YamlHeaderBlock.cs
  Microsoft.Toolkit.Parsers/Markdown/Helpers/Common.cs
  Microsoft.Toolkit.Services/Core/IAuthenticationBroker.cs
  Microsoft.Toolkit.Services/Exceptions/ConfigNullException.cs
  Microsoft.Toolkit.Services/Exceptions/OAuthKeysRevokedException.cs
  Microsoft.Toolkit.Services/PlatformSpecific/NETFramework/NetFrameworkAuthenticationBroker.cs
  Microsoft.Toolkit.Services/Services/LinkedIn/LinkedInDataProvider.cs
  Microsoft.Toolkit.Services/Services/LinkedIn/LinkedInService.cs
  Microsoft.Toolkit.Services/Services/MicrosoftTranslator/ITranslatorService.cs
  Microsoft.Toolkit.Services/Services/MicrosoftTranslator/ServiceLanguage.cs
  Microsoft.Toolkit.Services/Services/Twitter/Tweet.cs
  Microsoft.Toolkit.Services/Services/Twitter/TwitterDataProvider.cs
  Microsoft.Toolkit.Services/Services/Twitter/TwitterOAuthRequestBuilder.cs
  Microsoft.Toolkit.Services/Services/Twitter/TwitterPlaceBoundingBox.cs
  Microsoft.Toolkit.Services/Services/Twitter/TwitterService.cs
  Microsoft.Toolkit.Services/Services/Twitter/TwitterStreamEventType.cs
  Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/PlatformSpecificAnalyzerCS.cs
  Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/PlatformSpecificAnalyzerVB.cs
  Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/PlatformSpecificFixerCS.cs
  Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer/PlatformSpecificFixerVB.cs
  Microsoft.Toolkit.Uwp.SampleApp/Controls/SampleAppMarkdownRenderer.cs
  Microsoft.Toolkit.Uwp.SampleApp/Controls/XamlCodeEditor.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/Data/DataGridDataItem.cs
  Microsoft.Toolkit.Uwp.SampleApp/Models/Sample.cs
  Microsoft.Toolkit/Diagnostics/Guard.Comparable.Generic.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.cs
  Microsoft.Toolkit/Helpers/NotifyTaskCompletion.cs
  Microsoft.Toolkit/IncrementalLoadingCollection/IIncrementalSource.cs
Labels: documentation :page_with_curl:

#3407 Fixed rendering of markdown links with inline code
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/MarkdownTextBlock.xaml
  Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock/Render/MarkdownRenderer.Inlines.cs
Labels: auto merge, bug :bug:, controls :control_knobs:, markdown 📑

#3366 Changing DataGridItemAutomationPeer::GetNameCore & fixing DATAGRIDROWHEADER_stateNormalEditingRowFocused typo
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridCellAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridColumnHeaderAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridColumnHeadersPresenterAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridDetailsPresenterAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridGroupItemAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridItemAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridRowAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridRowGroupHeaderAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridRowHeaderAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/Automation/DataGridRowsPresenterAutomationPeer.cs
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridRowHeader.cs
Labels: DataGrid :capital_abcd:, auto merge, bug :bug:, needs attention :wave:

#3412 Fix spelling errors in .csproj and documentation files
  Microsoft.Toolkit.HighPerformance/Microsoft.Toolkit.HighPerformance.csproj
  Microsoft.Toolkit.Uwp.SampleApp/readme.md
  Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj
Labels: bug :bug:, documentation :page_with_curl:

#3408 Reduced memory usage in HighPerformance tests
  UnitTests/UnitTests.HighPerformance.Shared/Buffers/Internals/UnmanagedSpanOwner.cs
  UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ReadOnlySpanExtensions.Count.cs
  UnitTests/UnitTests.HighPerformance.Shared/Extensions/Test_ReadOnlySpanExtensions.cs
  UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_HashCode{T}.cs
  UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.For.cs
  UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.For2D.cs
  UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.In.cs
  UnitTests/UnitTests.HighPerformance.Shared/Helpers/Test_ParallelHelper.ForEach.Ref.cs
  UnitTests/UnitTests.HighPerformance.Shared/UnitTests.HighPerformance.Shared.projitems
Labels: CI/pipeline 🔬

#3410 Improved reliability of Task.GetResultOrDefault
  Microsoft.Toolkit/Extensions/TaskExtensions.cs
  UnitTests/UnitTests.Shared/Extensions/Test_TaskExtensions.cs
Labels: .NET Standard, bug :bug:, improvements :sparkles:, needs attention :wave:

#3413 Microsoft.Toolkit.Mvvm package (part 2)
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableObject.cs
  Microsoft.Toolkit.Mvvm/ComponentModel/ObservableRecipient.cs
  Microsoft.Toolkit.Mvvm/DependencyInjection/Ioc.cs
  Microsoft.Toolkit.Mvvm/Messaging/Messenger.cs
  Microsoft.Toolkit.Mvvm/Messaging/MessengerExtensions.cs
  Microsoft.Toolkit.Mvvm/Microsoft.Toolkit.Mvvm.csproj
Labels: .NET Standard, auto merge, bug :bug:, improvements :sparkles:, optimization ☄

#3401 GridSplitter accessibility issue fix
  Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.Events.cs
Labels: accessibility :wheelchair:, auto merge, bug :bug:

#3423 Fix Notifications library for C++ apps
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj
Labels: bug :bug:

#3346 ThrowHelper APIs
  Microsoft.Toolkit/Attributes/DoesNotReturnAttribute.cs
  Microsoft.Toolkit/Attributes/DoesNotReturnIfAttribute.cs
  Microsoft.Toolkit/Attributes/NotNullAttribute.cs
  Microsoft.Toolkit/Diagnostics/Generated/ThrowHelper.Collection.g.cs
  Microsoft.Toolkit/Diagnostics/Generated/ThrowHelper.Collection.tt
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.Collection.Generic.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.Comparable.Generic.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.Comparable.Numeric.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.IO.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.String.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.Tasks.cs
  Microsoft.Toolkit/Diagnostics/Internals/ThrowHelper.Guard.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.ThrowExceptions.cs
  Microsoft.Toolkit/Diagnostics/ThrowHelper.cs
  UnitTests/UnitTests.Shared/Diagnostics/Test_ThrowHelper.cs
  UnitTests/UnitTests.Shared/UnitTests.Shared.projitems
Labels: .NET Standard, feature :bulb:

#3439 Minor codegen improvements in Microsoft.Toolkit.Collections APIs
  Microsoft.Toolkit/Collections/ObservableGroupedCollectionExtensions.cs
  Microsoft.Toolkit/Collections/ReadOnlyObservableGroupedCollection.cs
Labels: .NET Standard, auto merge, needs attention :wave:, optimization ☄

#3452 Fix InAppNotification not working show/hide/show sequence
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification/InAppNotification.cs
Labels: bug :bug:, needs author feedback :memo:
