Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2021-05, with the labels that each got.

#3943 Fix ColorPicker CustomPaletteColors default property value
  Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPicker.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorToColorShadeConverter.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorToHexConverter.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ContrastBrushConverter.cs
  Microsoft.Toolkit.Uwp.UI/Converters/ColorToDisplayNameConverter.cs
Labels: bug :bug:, helpers :raised_hand:, hotfix 🌶, priority 🚩

#3960 Fix Incorrect usages of UnsetValue
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/AnimalToColorConverter.xaml.cs
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/EnumValuesExtension/EnumValuesExtensionCode.bind
  Microsoft.Toolkit.Uwp.UI/Converters/TaskResultConverter.cs
  Microsoft.Toolkit.Uwp.UI/Extensions/UIElementExtensions.cs
  UnitTests/UnitTests.UWP/Converters/Test_TaskResultConverter.cs
Labels: bug :bug:, hotfix 🌶, priority 🚩

#4012 Update for new branch name
  Directory.Build.props
  Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.nuspec
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/MarkdownTextBlock/InitialContent.md
  Microsoft.Toolkit.Uwp.SampleApp/readme.md
  Microsoft.Toolkit.Uwp.UI.Controls.Core.Design/Common/MetadataRegistrationBase.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout.Design/Common/MetadataRegistrationBase.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj
  azure-pipelines.yml
  readme.md
  version.json
Labels: priority 🚩

#4014 Fixed ExpressionNode.EnsureReferenceInfo() crash with .NET Native
  Microsoft.Toolkit.Uwp.UI.Animations/Expressions/ExpressionNodes/ExpressionNode.cs
  Microsoft.Toolkit.Uwp.UI.Animations/Extensions/System/GuidExtensions.cs
  Microsoft.Toolkit.Uwp.UI.Media/Extensions/System/GuidExtensions.cs
  Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Effects.Internals.cs
  Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Effects.cs
  Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Initialization.cs
  Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.Merge.cs
  Microsoft.Toolkit.Uwp.UI.Media/Pipelines/PipelineBuilder.cs
Labels: animations :izakaya_lantern:, auto merge :zap:, hotfix 🌶, priority 🚩

#3852 incremnenralLoading-pageIndex-fix
  Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
  UnitTests/UnitTests.UWP/UI/Collection/DataSource.cs
  UnitTests/UnitTests.UWP/UI/Collection/Test_IncrementalLoadingCollection.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: auto merge :zap:, bug :bug:, hotfix 🌶, priority 🚩

#4008 TextToolbar shortcuts should not be triggered by AltGr key
  Microsoft.Toolkit.Uwp.UI.Controls.Core/TextToolbar/TextToolbar.Events.cs
Labels: accessibility :wheelchair:, hotfix 🌶, sdkcheck :checkered_flag:

#4020 ImageEx: test and fix setting Source
  Microsoft.Toolkit.Uwp.UI.Controls.Core/ImageEx/ImageExBase.Source.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Core/ImageEx/ImageExBase.cs
  UnitTests/UnitTests.UWP/Assets/StoreLogo.embeded.png
  UnitTests/UnitTests.UWP/UI/Controls/Test_ImageEx.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: bug :bug:, controls :control_knobs:, hotfix 🌶, priority 🚩

#3926 Rangeselector tests
  UnitTests/UnitTests.UWP/IsExternalInit.cs
  UnitTests/UnitTests.UWP/UI/Controls/Test_RangeSelector.cs
  UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Labels: auto merge :zap:, testing :building_construction:
