Repository CommunityToolkit/WindowsCommunityToolkit, pull requests merged in 2022-09, with the labels that each got.

#4549 Fix AttachedDropShadow size changes abnormally
  Microsoft.Toolkit.Uwp.UI/Shadows/AttachedDropShadow.cs
Labels: bug :bug:, hotfix 🌶

#4738 ListDetailsView.ListPaneWidth Null check fix
  Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ListDetailsView/ListDetailsView.bind
  Microsoft.Toolkit.Uwp.UI.Controls.Layout/ListDetailsView/ListDetailsView.cs
Labels: bug :bug:, controls :control_knobs:, WinUI :diamond_shape_with_a_dot_inside:

#4760 Updated expired UI Test certificate. Expires 9/8/2023.
  UITests/UITests.App/Package.appxmanifest
  UITests/UITests.App/UITests.App.csproj
  UITests/UITests.App/UITests.App.pfx
  UITests/UITests.Tests.Shared/TestAssembly.cs
  UITests/UITests.Tests.Shared/UITestBase.cs
Labels: bug :bug:

#4757 AttachedDropShadowCrashFix
  Microsoft.Toolkit.Uwp.UI/Shadows/AttachedShadowBase.cs
Labels: bug :bug:, sample app 🖼

#4720 Fixed ImageCropper AspectRatio not updating on image load
  Microsoft.Toolkit.Uwp.UI.Controls.Media/ImageCropper/ImageCropper.Events.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Media/ImageCropper/ImageCropper.Logic.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Media/ImageCropper/ImageCropper.Properties.cs
  Microsoft.Toolkit.Uwp.UI.Controls.Media/ImageCropper/ImageCropper.cs
Labels: bug :bug:, controls :control_knobs:, for-review :book:, hotfix 🌶
